CREATE TABLE soundlyinvest_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

ALTER TABLE soundlyinvest_reports
    ADD COLUMN
        user_id INTEGER REFERENCES soundlyinvest_users(id)
        ON DELETE SET NULL;